# POST http://localhost:8088/api/v1/auth/register
# Content-Type: application/json

# {
#   "name": "ashs",
#   "password": "ssesadcsursddfepasswaord123",
#   "email": "ash@assaaddfdssdah.com"
# }

# POST http://localhost:8088/api/v1/events
# Content-Type: application/json

# {
#   "ownerId": 3,
#   "name": "new s okhjssa",
#   "description": "This sxis a new event created via API.",
#   "date": "2023-10-01T10:00:00Z",
#   "location": "Nw Yossxsxrk"
# }

# GET  http://localhost:8088/api/v1/events

# GET http://localhost:8088/api/v1/events/6

# PUT http://localhost:8088/api/v1/events/1
# Content-Type: application/json

# {
#     "name": " cahnged",
#     "description": "This a new event created via API.",
#     "date": "2023-10-01T10:00:00Z",
#     "ownerId": 3
# }

# DELETE  http://localhost:8088/api/v1/events/3

# GET http://localhost:8088/api/v1/auth/users

GET http://localhost:8088/api/v1/events/attendees/5

# GET http://localhost:8088/api/v1/attendees/events/3

# DELETE   http://localhost:8088/api/v1/events/attendees/5/3

# POST http://localhost:8088/api/v1/events/5/attendees/3
# Content-Type: application/json

