# POST http://localhost:8088/api/v1/auth/register
# Content-Type: application/json

# {
#   "name": "ash",
#   "password": "ssesadcsursddfepasswaord123",
#   "email": "ash@assaaddfdsdah.com"
# }

POST http://localhost:8088/api/v1/events
Content-Type: application/json

{
  "ownerId": 1,
  "name": "event es okssa",
  "description": "This sxis a new event created via API.",
  "date": "2023-10-01T10:00:00Z",
  "location": "Nscsew Yossxsxrk"
}

GET  http://localhost:8088/api/v1/events